source "https://rubygems.org"

# Load local gem
gemspec

gem "standard"
gem "bundle"

group :development do
  gem "rake"
  gem "minitest"
  gem "rspec"
  gem "aruba"
  gem "pry-byebug"

  gem "guard"
  gem "guard-shell"
  gem "guard-rspec"
end
